# Generated by Django 2.2.1 on 2019-05-23 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lijek',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=100)),
                ('cijena', models.FloatField(default=None)),
                ('slika', models.ImageField(blank=True, default='default.png', upload_to='media/')),
                ('recept', models.BooleanField(default=False)),
                ('opis', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique='True')),
                ('kod', models.CharField(max_length=50)),
                ('namjena', models.CharField(choices=[('bol', 'bol'), ('prehlada', 'prehlada'), ('stres', 'stres'), ('otpornost', 'otpornost'), ('dijabetes', 'dijabetes'), ('rak', 'rak')], default='none', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Snizenje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.FloatField(default=None)),
                ('datum', models.DateField(default=datetime.date.today)),
                ('lijek', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Lijek')),
            ],
        ),
    ]
