# Generated by Django 2.2.2 on 2019-07-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190525_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lijekovi',
            field=models.ManyToManyField(blank=True, to='app.Lijek'),
        ),
    ]
