# Generated by Django 2.2.2 on 2019-07-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_faktura_lijeknarudzba'),
    ]

    operations = [
        migrations.AddField(
            model_name='lijeknarudzba',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
