# Generated by Django 2.2.1 on 2019-05-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190523_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lijek',
            name='namjena',
            field=models.CharField(choices=[('bol', 'bol'), ('prehlada', 'prehlada'), ('stres', 'stres'), ('otpornost', 'otpornost'), ('dijabetes', 'dijabetes'), ('rak', 'rak'), ('upala', 'upala')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='snizenje',
            name='iznos',
            field=models.IntegerField(),
        ),
    ]
